ImtahanLast/ImtahanLast/Models/Doctors.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ImtahanLast.Models
{
    public class Doctors
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
    }
}

ImtahanLast/ImtahanLast/Areas/Admin/Controllers/DoctorController.cs
using ImtahanLast.DAL;
using ImtahanLast.Models;
using ImtahanLast.Utilize;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ImtahanLast.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DoctorController : Controller
    {
        public readonly AppDbContext _context;
        public readonly IWebHostEnvironment _env;
        public DoctorController(AppDbContext context , IWebHostEnvironment env)
        {
            _context = context;
            _env = env; 
        }
        public ActionResult Index()
        {
            List<Doctors> doctors = _context.Doctors.ToList();
            return View(doctors);
        }

        // GET: DoctorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DoctorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DoctorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Doctors doctor)
        {
              
            if (!ModelState.IsValid) return View();

            if (doctor.Image !=null)
            {
                if (doctor.Image.CheckSize(500))
                {
                    ModelState.AddModelError("", "Size coxdu");
                    return View();
                }
                if (!doctor.Image.CheckType("image/"))
                {
                    ModelState.AddModelError("", "type sehvdir");
                    return View();

                }
                doctor.ImageUrl = doctor.Image.SaveImg(Path.Combine(_env.WebRootPath, "assets", "DoctorImg"));
            }
            _context.Doctors.Add(doctor);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: DoctorController/Edit/5
        public ActionResult Edit(int id)
        {
            Doctors dc = _context.Doctors.Find(id);
            if (dc == null)
            {
                return View();
            }
            return View(dc);
        }

        // POST: DoctorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Doctors doctor)
        {
            if (id != doctor.Id) return View();
            Doctors DbDc = _context.Doctors.Find(id);
            if (DbDc == null)
            {
                return BadRequest();
            }
           
            if (doctor.Image !=null)
            {
                if (doctor.Image.CheckSize(500))
                {
                    ModelState.AddModelError("", "Size coxdu");
                    return View();
                }
                if (!doctor.Image.CheckType("image/"))
                {
                    ModelState.AddModelError("", "type sehvdir");
                    return View();

                }
                FileManager.DeleteFile(Path.Combine(_env.WebRootPath, "assets", "DoctorImg",DbDc.ImageUrl));
                DbDc.ImageUrl = doctor.Image.SaveImg(Path.Combine(_env.WebRootPath ,"assets", "DoctorImg"));

            }
            DbDc.Name = doctor.Name;
            DbDc.Title = doctor.Title;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: DoctorController/Delete/5
        public ActionResult Delete(int id)
        {
            Doctors dc = _context.Doctors.Find(id);
            if (dc.Image !=null)
            {
                 FileManager.DeleteFile(Path.Combine(_env.WebRootPath, "assets", "DoctorImg", dc.ImageUrl));
            }
            _context.Doctors.Remove(dc);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

ImtahanLast/ImtahanLast/Areas/Admin/Views/Doctor/Create.cshtml
@model Doctors
@{
    ViewData["Title"] = "Create";
}
<div class="card-body">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <input type="text" asp-for="Name" class="form-control" placeholder="Enter Name">
        </div>
        <div class="form-group">
            <input type="text" asp-for="Title" class="form-control" placeholder="Enter Title">
        </div>
        <div class="form-group">
            <input type="file" asp-for="Image" class="form-control" >
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
        <div asp-validation-summary="ModelOnly"></div>
    </form>

</div>

ImtahanLast/ImtahanLast/Areas/Admin/Views/Doctor/Edit.cshtml
@model Doctors
@{
    ViewData["Title"] = "Edit";
}

<div class="card-body">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <input type="text" asp-for="Name" class="form-control" placeholder="Enter Name">
        </div>
        <div class="form-group">
            <input type="text" asp-for="Title" class="form-control" placeholder="Enter Title">
        </div>
        <div class="form-group">
            <input type="file" asp-for="Image" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
        <div asp-validation-summary="ModelOnly"></div>
    </form>

</div>

ImtahanLast/ImtahanLast/Areas/Admin/Views/Doctor/Index.cshtml
@model List<Doctors>
@{
    ViewData["Title"] = "Index";
}
<div class="card-body">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <a class="btn btn-success-soft mb-1" asp-controller="Doctor" asp-action="Create">Add</a>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Title</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.Name</td>
                    <td>@item.Title</td>

                    <td>
                        <img style="width:100px;" src="~/assets/DoctorImg/@item.ImageUrl" alt="">
                    </td>
                    <td><a class="btn btn-primary-soft" asp-controller="Doctor" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                    <td><a class="btn btn-danger-soft" asp-controller="Doctor" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
                </tr>
                }

            </tbody>
        </table>
    </div>
</div>