ImtahanLast/ImtahanLast/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImtahanLast.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ImtahanLast/ImtahanLast/Controllers/AuthController.cs
using ImtahanLast.Models;
using ImtahanLast.ViewModels.Autho;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImtahanLast.Controllers
{
    public class AuthController : Controller
    {
        public readonly UserManager<AppUser> _userManager;
        public readonly SignInManager<AppUser> _signInManager;
        public AuthController(UserManager<AppUser> userManager,SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterVM register)
        {
            if (!ModelState.IsValid) return View(register);

            if (!register.Email.Contains("@"))
            {
                ModelState.AddModelError("", "Email is valid");
                return View();
            }
            AppUser newUser = new AppUser()
            {
                FirstName = register.FirstName,
                LastName = register.LastName,
                Email = register.Email,
                UserName = register.UserName,
            };
            var result = await _userManager.CreateAsync(newUser, register.Password);
            if (!result.Succeeded)
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                    return View();
                }
            }
            return RedirectToAction("Index", "Home");
            
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginVM login)
        {
            AppUser user;
            if (login.UserNameOrEmail.Contains("@"))
            {
                user = await _userManager.FindByEmailAsync(login.UserNameOrEmail);
            }
            else
            {
                user = await _userManager.FindByNameAsync(login.UserNameOrEmail);
            }
            if (user == null)
            {
                ModelState.AddModelError("", "user is valid");
                return View();
            }
            var result = await _signInManager.PasswordSignInAsync(user, login.Password, login.RememberMe, true);
            return RedirectToAction("Index", "Home");

        }
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

ImtahanLast/ImtahanLast/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,100;1,300;1,700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="~/assets/css/style.css">
</head>

<body>
    <!-- Header Start -->
    <header>
        <section id="day">
            <nav class="navbar">
                <div class="container">
                    <a class="navbar-brand">
                        <i class="fa-solid fa-clock"></i> <span>
                            Monday - Saturday, 8AM to
                            10PM
                        </span>
                    </a>
                    <div class="">
                        <i class="fa-solid fa-mobile-screen-button"></i>
                        <span>Call us now +1 5589 55488 55</span>
                    </div>
                </div>

            </nav>
            </div>
        </section>
        <section id="navigation">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container">
                    <a class="navbar-brand" href="#"><img src="./assets/img/logo.png" alt=""></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Departments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Doctors</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Dashboard" asp-area="Admin">AdminPanel</a>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Auth" asp-action="Register">@User.Identity.Name</a>

                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Auth" asp-action="LogOut">LogOut</a>

                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                            }

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    Dropdown
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Doctors</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="btn MakeAn">Make An Appointment</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </section>
    </header>
    <!-- Header End -->

    @RenderBody()

    <!-- Footer -->
    <footer style="padding:50px;" class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
                <span>Get connected with us on social networks:</span>
            </div>
            <!-- Left -->
            <!-- Right -->
            <div>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-google"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->
        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 style="font-size: 24px ;" class="text-uppercase fw-bold mb-4">
                            Medicio
                        </h6>
                        <p>
                            A108 Adam Street
                        </p>
                        <P>NY 535022, USA</P>
                        <p><strong>Phone:</strong>+1 5589 55488 55</p>
                        <p><strong>Email::</strong>info@example.com</p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful Links
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">
                                Home
                            </a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">About us</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">
                                Services
                            </a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">
                                Terms of service
                            </a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">
                                Privacy policy
                            </a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Our Services

                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Web Design</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Web Development</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Product Management</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Marketing</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">
                                Graphic Design
                            </a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Our Newsletter
                        </h6>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control">
                            <span class="input-group-text"><button class="btn btn-primary">Subscribe</button></span>
                        </div>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © Copyright Medicio. All Rights Reserved
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <!-- Main End -->




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
</body>

</html>